"""empty message

Revision ID: 0a9eff639dcb
Revises: 7f56a4152014
Create Date: 2021-04-02 19:58:13.576973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9eff639dcb'
down_revision = '7f56a4152014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abusefilter', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abusefilter', 'private')
    # ### end Alembic commands ###
