"""empty message

Revision ID: 1729186d9584
Revises: 0a9eff639dcb
Create Date: 2021-06-18 09:34:28.530834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1729186d9584'
down_revision = '0a9eff639dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abusefilter', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abusefilter', 'deleted')
    # ### end Alembic commands ###
