"""empty message

Revision ID: 7f56a4152014
Revises: 810024f0bf79
Create Date: 2021-04-02 19:03:09.984515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f56a4152014'
down_revision = '810024f0bf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abusefilter', sa.Column('wiki_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abusefilter', 'wiki_url')
    # ### end Alembic commands ###
