"""empty message

Revision ID: 810024f0bf79
Revises: dc3bf6bde331
Create Date: 2021-04-02 18:51:56.283965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810024f0bf79'
down_revision = 'dc3bf6bde331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_manually_authorized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
