MESSAGES_DIR: ../messages
SECRET_KEY: something
SQLALCHEMY_DATABASE_URI: mysql://root:password@localhost/search_filters?charset=utf8mb4
CONSUMER_KEY: b85ce6a71a2830235974fe8c2e8482ab # localhost credentials
CONSUMER_SECRET: 99006db2f4f7ae5a55fc15733ff93d8f403fdff0 # localhost credentials
SERVICE_ACCOUNT_CONSUMER_TOKEN: FIXME
SERVICE_ACCOUNT_CONSUMER_SECRET: FIXME
SERVICE_ACCOUNT_ACCESS_TOKEN: FIXME
SERVICE_ACCOUNT_ACCESS_SECRET: FIXME
OAUTH_MWURI: https://meta.wikimedia.org/w
